create or replace cortex search service SALESCONVERSATIONSEARCH
	ON TRANSCRIPT_TEXT
	attributes CUSTOMER_NAME,DEAL_STAGE,SALES_REP,CONVERSATION_DATE,DEAL_VALUE,PRODUCT_LINE
	warehouse='COMPUTE_WH'
	target_lag='1 hour'
	refresh_mode=INCREMENTAL
	as (
	SELECT
		TRANSCRIPT_TEXT,
		CUSTOMER_NAME,
		DEAL_STAGE,
		SALES_REP,
		CONVERSATION_DATE,
		DEAL_VALUE,
		PRODUCT_LINE,
		CONVERSATION_ID
	FROM SALES_INTELLIGENCE.DATA.SALES_CONVERSATIONS
);